### ISSUE TITLE
fyi unicodes in readme.md

### ISSUE THREAD

**Issue by pwais** [WU-CVGL/BAD-Gaussians#1]
just fyi these don't seem to be fully portable, mebbe try normal markdown instead of unicodes

![Screen Shot 2024-03-19 at 3 43 44 PM](https://github.com/WU-CVGL/BAD-Gaussians/assets/218145/5d76161e-7e9d-48d8-ab07-e9b198ceeba1)

**Comment by wangpeng000** [comment]
The error appears to be specific to the Chrome browser on Mac (I'm not sure, but the Safari is OK), likely stemming from the utilization of a particular font. We have addressed this issue by adjusting the fonts, and it should be resolved now.

**Comment by LingzheZhao** [comment]
Glad you pointed it out! I believe it's resolved now
