### ISSUE TITLE
Error: --pipeline.model.rasterize_mode "classic"

### ISSUE THREAD

**Issue by chensh1127** [WU-CVGL/BAD-Gaussians#12]
Hey ，
My code is : 
`ns-train bad-gaussians --data ./outputdir/coser2 --vis viewer+tensorboard nerfstudio-data --eval_mode "all" --pipeline.model.rasterize_mode "classic"`

the treminal is: 
![image](https://github.com/WU-CVGL/BAD-Gaussians/assets/65758969/1a205398-564e-48ef-99cd-2fb6196c9743)

**Comment by LingzheZhao** [comment]
Hi, the arguments after `nerfstudio-data` will be passed to the NerfstudioDataParser, thus we must put `--pipeline.model.rasterize_mode "classic"` before it:

```sh
ns-train bad-gaussians --data ./outputdir/coser2 --pipeline.model.rasterize_mode "classic" --vis viewer+tensorboard nerfstudio-data --eval_mode "all"
```

**Comment by chensh1127** [comment]
it works , thank you
