### ISSUE TITLE
MBA-VO 数据集

### ISSUE THREAD

**Issue by xiaoyaolovlife** [WU-CVGL/BAD-Gaussians#17]
您好，感谢你们出色的工作！我复现的过程中未找到文章中提到的MBA-VO数据集，请问能否给个下载链接
![image](https://github.com/WU-CVGL/BAD-Gaussians/assets/170327167/14cca943-a70b-4d68-8482-09b4eaeaa5aa)

**Comment by LingzheZhao** [comment]
您好!感谢您对我们工作的关注。文章中所使用的两个MBA-VO序列都可以在README中提供的Onedrive链接中找到，在`bad-nerf-gtK-colmap-nvs`文件夹下，分别是`roomblur_low`和`roomblur_high`。
