### ISSUE TITLE
What is the difference betwenn the BAD-NeRF and BAD-Gaussians.

### ISSUE THREAD

**Issue by chenkang455** [WU-CVGL/BAD-Gaussians#21]

**Comment by LingzheZhao** [comment]
Hello, thanks for your interest in our work.

BAD-Gaussians is the first open-source project that provides motion-deblurring for 3DGS. It is aimed to become the successor of BAD-NeRF, for its much faster training speed, real-time rendering capability and superior performance.

This code base was built on top of our [previous open-source project](https://github.com/WU-CVGL/Bad-RFs/) that re-implements BAD-NeRF in the [`nerfstudio`](https://github.com/nerfstudio-project/) framework. The core code has been completely refactored compared to BAD-NeRF, and we tried our best to keep the code base simple and easy to follow, following the the style guides of the community.

**Comment by chenkang455** [comment]
> Hello, thanks for your interest in our work.
> 
> BAD-Gaussians is the first open-source project that provides motion-deblurring for 3DGS. It is aimed to become the successor of BAD-NeRF, for its much faster training speed, real-time rendering capability and superior performance.
> 
> This code base was built on top of our [previous open-source project](https://github.com/WU-CVGL/Bad-RFs/) that re-implements BAD-NeRF in the [`nerfstudio`](https://github.com/nerfstudio-project/) framework. The core code has been completely refactored compared to BAD-NeRF, and we tried our best to keep the code base simple and easy to follow, following the the style guides of the community.

Thanks a lot for your detailed response!

**Comment by chenkang455** [comment]
Hi, @LingzheZhao sry to bother you again. I am curious about the performance of BAD-Gaussian on the 360 scene like lego. Can the BAD-Gaussian converge nicely on the 360 scene?

Thx a lot!

**Comment by LingzheZhao** [comment]
Hi, @chenkang455, yes it can, because 3DGS itself works nicely on 360 (object-centric) scenes, unlike original BAD-NeRF was designed for LLFF datasets with NDC [scene contraction](https://docs.nerf.studio/nerfology/model_components/visualize_spatial_distortions.html#scene-contraction).

In fact, lots of NeRF-based implicit methods, need special modeling of scene contraction, while 3DGS-based methods usually do not.

**Comment by chenkang455** [comment]
> Hi, @chenkang455, yes it can, because 3DGS itself works nicely on 360 (object-centric) scenes, unlike original BAD-NeRF was designed for LLFF datasets with NDC [scene contraction](https://docs.nerf.studio/nerfology/model_components/visualize_spatial_distortions.html#scene-contraction).
> 
> In fact, lots of NeRF-based implicit methods, need special modeling of scene contraction, while 3DGS-based methods usually do not.

I get it, thanks for your detailed response again. 😊
