### ISSUE TITLE
`ns-train bad-gaussians -h` gives error

### ISSUE THREAD

**Issue by ichsan2895** [WU-CVGL/BAD-Gaussians#5]
The code that causes error:
```
>> ns-train bad-gaussians -h
Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/configs/method_configs.py", line 724, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/BAD-GAUSSIAN/BAD-Gaussians/bad_gaussians/bad_config_method.py", line 12, in <module>
    from bad_gaussians.image_restoration_dataparser import ImageRestorationDataParserConfig
ModuleNotFoundError: No module named 'bad_gaussians.image_restoration_dataparser'
```

How to install it
```
# clean up previous version
pip uninstall gsplat bad-gaussians

git clone --branch 8e0c68754b2c440e2d83864fac586cddcac52dc4 https://github.com/nerfstudio-project/nerfstudio
cd nerfstudio
pip install -e .

pip install git+https://github.com/LingzheZhao/gsplat

cd ../

git clone https://github.com/WU-CVGL/BAD-Gaussians
cd BAD-Gaussians
pip install -e .
```

System information:
```
Ubuntu 22.04 LTS
Python 3.10
Pytorch 2.0.1+cu118
```

This error happens after this commit https://github.com/WU-CVGL/BAD-Gaussians/commit/25155be35f3c2dbdb13af1fb439e90d0523c98ba

**Comment by LingzheZhao** [comment]
Sry this is caused by recent remove of `image_restoration_dataparser`, as it may have caused some confusion in #3. You can first uninstall the `bad_gaussians`:

```
pip uninstall bad_gaussians
```

Then reinstall it, the problem should be gone.

(This only happens if you have installed it before)

**Comment by Volleria** [comment]
I also meet similar issues while running the code

It runs on WSL

**Comment by Volleria** [comment]
when l run this command
`ns-train bad-gaussians -h`
I also meet similar issues ：
`╭─ Parsing error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Argument                                                                                                                                                     │
│ {depth-nerfacto,dnerf,generfacto,instant-ngp,instant-ngp-bounded,mipnerf,nerfacto,nerfacto-big,nerfacto-huge,neus,neus-facto,phototourism,semantic-nerfw,spl │
│ atfacto,splatfacto-big,tensorf,vanilla-nerf,igs2gs,in2n,in2n-small,in2n-tiny,kplanes,kplanes-dynamic,lerf,lerf-big,lerf-lite,nerfplayer-nerfacto,nerfplayer- │
│ ngp,pynerf,pynerf-occupancy-grid,pynerf-synthetic,seathru-nerf,seathru-nerf-lite,tetra-nerf,tetra-nerf-original,volinga,zipnerf}: invalid choice:            │
│ 'bad-gaussians' (choose from 'depth-nerfacto', 'dnerf', 'generfacto', 'instant-ngp', 'instant-ngp-bounded', 'mipnerf', 'nerfacto', 'nerfacto-big',           │
│ 'nerfacto-huge', 'neus', 'neus-facto', 'phototourism', 'semantic-nerfw', 'splatfacto', 'splatfacto-big', 'tensorf', 'vanilla-nerf', 'igs2gs', 'in2n',        │
│ 'in2n-small', 'in2n-tiny', 'kplanes', 'kplanes-dynamic', 'lerf', 'lerf-big', 'lerf-lite', 'nerfplayer-nerfacto', 'nerfplayer-ngp', 'pynerf',                 │
│ 'pynerf-occupancy-grid', 'pynerf-synthetic', 'seathru-nerf', 'seathru-nerf-lite', 'tetra-nerf', 'tetra-nerf-original', 'volinga', 'zipnerf')                 │
│ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── │
│ For full helptext, run ns-train --help                                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯`

It runs on WSL

**Comment by LingzheZhao** [comment]
Hi, @Volleria I haven't try WSL but it seems `bad_gaussians` was not correctly installed and the `nerfstudio` cannot find it. Could you run

```bash
pip list | grep bad
```

to check if `bad_gaussians` is installed?

**Comment by chensh1127** [comment]
l run this command  `ns-train bad-gaussians -h,`  I meet the same error.  My python version is 3.08,  Pytorch 2.0.1+cu118.  I tried `pip uninstall bad_gaussians`,  then `pip install -e . `  it does not work.

**Comment by LingzheZhao** [comment]
@chensh1127 @Volleria  Hi, I am trying to reproduce your errors. Could you try upgrading `setuptools` & `pip` and install `bad_gaussians` again?

```bash
pip install --upgrade pip setuptools
pip uninstall bad_gaussians
```

```
# cd /path/to/BAD-Gaussians if you are not in it
pip install -e .
ns-train bad-gaussians -h
```

**Comment by LingzheZhao** [comment]
@ichsan2895 Sorry my mistake here, I forgot to commit the [bad_config_method.py](https://github.com/WU-CVGL/BAD-Gaussians/commit/d6d76f75bbbc69def17ae5f7445c06c76542d458#diff-fb3700f4924e19a2c0a74b2463beb75fbcd194698685ad1ed5807de1deff1c74)

**Comment by Volleria** [comment]
> @chensh1127 @Volleria Hi, I am trying to reproduce the errors. Could you try upgrading `setuptools` & `pip` and install `bad_gaussians` again?
> 
> ```shell
> pip install --upgrade pip setuptools
> pip uninstall bad_gaussians
> ```
> 
> ```
> # cd /path/to/BAD-Gaussians if you are not in it
> git pull
> pip install -e .
> ns-train bad-gaussians -h
> ```

thanks!  it runs correctly now
