### ISSUE TITLE
nerfstudio 1.0.3 requires gsplat>=0.1.9, but you have gsplat 0.1.8 which is incompatible

### ISSUE THREAD

**Issue by rozumden** [WU-CVGL/BAD-Gaussians#8]
Hello,

I have troubles running your code. It seems that due to the recent update of nerfstudio, the code no longer runs. Nerfstudio 1.0.3 requires gsplat 0.1.9 or higher. However, your fork depends on gsplat 0.1.8.

Please see the following error message:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nerfstudio 1.0.3 requires gsplat>=0.1.9, but you have gsplat 0.1.8 which is incompatible.

Best regards
Denys

**Comment by LingzheZhao** [comment]
Hello Denys, thank you for your interest in our work! I have updated the code following `nerfstudio 1.0.3`, I can confirm it works perfectly now. Note that this repo no longer necessarily depends on our fork of gsplat now, as they have merged the related PRs.
